#!/bin/bash
#
# httpd        Startup script for the Apache HTTP Server
#
# description: The Apache HTTP Server is an efficient and extensible  \
#	       server implementing the current HTTP standards.
# processname: httpd
# config: /etc/apache2/httpd.conf
# pidfile: /var/run/apache2/httpd.pid
#
#
# Path to the apachectl script, server binary, and short-form for messages.
apachectl=/usr/bin/apachectl
httpd=${HTTPD-/usr/bin/httpd}
prog=httpd
pidfile=${PIDFILE-/var/run/apache2/httpd.pid}
RETVAL=0

start() {
        echo -n $"Starting $prog: "
        $apachectl -k start
        RETVAL=$?
        echo
        return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	$apachectl -k stop
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${pidfile}
}

reload() {
    echo -n $"Reloading $prog: "
    apache -k graceful 
    echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
    $apachectl status    
	;;
  restart)
	stop
	start
	;;
  force-reload|reload)
        reload
	;;
  graceful|help|configtest|fullstatus)
	$apachectl $@
	RETVAL=$?
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|reload|status|fullstatus|graceful|help|configtest}"
	RETVAL=2
esac

exit $RETVAL
