#!/usr/bin/env perl
# This script is released under GPL V2+
open(FILEREAD, "< /home/yoander/projects/cake/.perms");
my @arr;
while (<FILEREAD>) {
	my($line) = $_;
	chomp($line);
	push(@arr,$line);
}
close FILEREAD;
exit join(' ',@arr); 
