#!/bin/bash
rsync -e ssh -avz -h -h SRC_DIR DEST_DIR

rsync -avzm --no-A --no-o --no-g --delete-after --filter="- cache" --filter="- /lib/model" --filter="- log" --filter="+ .htaccess" --filter="- .*" --filter="- Thumbs.db" --filter="- nbproject" /var/www/vhosts/$1 /mnt/projects/

rsync -e ssh -avzm --no-A --no-o --chmod=ug-s,Dg=rx,Fg=r,o-rwx --delete --filter="- cache/" --filter="- .cache/" --filter="- test/" --filter="- tests/" --filter="- .project" --filter="- .settings" --filter="- Thumbs.db" --filter="- .metadata/" --filter="- log/" --filter="- logs/" --filter="- rsync-filter.txt" --filter=": /rsync-filter.txt" /var/www/vhosts/smc/images/photos/hotels/ solmeliacuba.com:/var/www/html/images/photos/hotels/

rsync -e ssh -avzm --no-A --no-o --chmod=ug-s,Dg=rx,Fg=r,o-rwx --delete --filter="- cache/" --filter="- .cache/" --filter="- test/" --filter="- tests/" --filter="- .project" --filter="- .settings" --filter="- Thumbs.db" --filter="- .metadata/" --filter="- log/" --filter="- logs/" --filter="- rsync-filter.txt" --filter=": /rsync-filter.txt" /var/www/vhosts/smc/travel-professionals/downloads/videos/ solmeliacuba.com:/var/www/html/travel-professionals/downloads/videos/

/usr/bin/rsync -avzmh --no-A --no-o --no-g --chmod=Dg=rwx,Fg=r,o=rwx --delete-after --filter='protect symfony' --filter 'protect lib/model/om/' --filter 'protect lib/model/map/' --filter 'protect cache/' --filter 'protect log/' --filter='- cache/' --filter='- .cache/' --filter='- test/' --filter='- tests/' --filter='- Thumbs.db' --filter='- log/' --filter='- *.cmd' --filter='- logs/' --filter='- rsync-filter.txt' --filter=': /rsync-filter.txt' --filter='+ .htaccess' --filter='- .*' $PRJ /opt/lampp/htdocs/
