#!/usr/bin/env bash
target=$(pwd)
user=nobody
group=nogroup

# ACL target file
if [[ '' != "$1" ]]; then
    if [[ ! -e "$1" ]]; then
        echo "File no exists: $1"
        exit 1
    fi
    target="$1"
fi

# ACL target user and group
if [[ "$2" =~ ([[:alpha:]]*-?[[:alpha:]]*):([[:alpha:]]*-?[[:alpha:]]*) ]]; then
    user=${BASH_REMATCH[1]}
    group=${BASH_REMATCH[2]}
elif [[ '' != "$2" ]]; then
    user="$2"
    group=
fi

if ! grep "^$user:" /etc/passwd 1> /dev/null; then
    echo "User not exists: $user"
        exit 2
fi

if [[ '' != $group ]] && ! grep "^$group:" /etc/group 1> /dev/null; then
    echo "Group not exists: $group"
    exit 3
fi

echo Full acl will be set to "$target", user: "$user", group: "$group"

read -p "Do you want to continue [y|n]:" answer

    case "$answer" in
    [yY1])
        if [[ -f $target ]]; then
            if [[ '' != $group ]]; then
                setfacl -m u::rw,g::rw,u:$user:rw,g:$group:rw,o:r $target
            else
                setfacl -m u::rw,g::rw,u:$user:rw,o:r $target
            fi
        elif [[ -d $target ]]; then
            if [[ '' != $group ]]; then
                find "$target" -type d -print0 | xargs -0 setfacl --set u::rwx,g::rxw,u:$user:rwx,g:$group:rwx,o:rx,m:rwx,d:u::rwx,d:g::rwx,d:u:$user:rwx,d:g:$group:rwx,d:o:rx,d:m:rwx
                find "$target" -type f -print0 | xargs -0 -I{} setfacl --set u::rw,g::rw,u:$user:rw,g:$group:rw,o:r,m:rw {}
            else
                find "$target" -type d -print0 | xargs -0 setfacl --set u::rwx,g::rwx,u:$user:rwx,o:rx,m:rwx,d:u::rwx,d:g::rwx,d:u:$user:rwx,d:o:rx,d:m:rwx
                find "$target" -type f -print0 | xargs -0 -I{} setfacl --set u::rw,g::rw,u:$user:rw,o:r,m:rw {}
            fi
        fi
        ;;
    [nN0])
        exit 0;
        ;;
    # error check
    *) echo -e "%b" "Unexpected answer: $answer" >&2 ;;
esac

exit 0
