#!/usr/bin/env bash 

# Connected?
if ping -c 5 8.8.8.8 > /dev/null 2>&1; then 
    exit 0
# Not connected? 
else
    # if pppd is zombie then kill it 
    PID=$(pgrep -x pppd)
    [[ '' != $PID ]] && kill -9 $PID
fi

# Launch dialup connection
sleep 2s
pon $1
